# Generated by Django 5.2.4 on 2025-07-15 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_comment_post_created_at_post_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="post_comment",
            ),
            preserve_default=False,
        ),
    ]
