# Generated by Django 5.2.4 on 2025-07-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=199),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="blog.category",
                verbose_name="category_name",
            ),
        ),
    ]
