# Generated by Django 5.2.4 on 2025-07-15 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_status_alter_comment_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
            ),
        ),
    ]
