# Generated by Django 5.2.4 on 2025-07-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_rating_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PUBLISHED", "Published"),
                    ("UNPUBLISHED", "Unpublished"),
                ],
                default="PENDING",
            ),
        ),
    ]
